esphome:
  name: epaper-screen
  friendly_name: epaper-screen

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

deep_sleep:
  run_duration: 90s       # give ESP32 1.5 minutes to connect and get HA data
  sleep_duration: 1800s   # sleep 30 minutes

logger:

api:
  encryption:
    key: "="

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Epaper-Screen Fallback Hotspot"
    password: ""

captive_portal:

image:
  - file: /config/esphome/images/01d.png
    id: w01d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/01n.png
    id: w01n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/02d.png
    id: w02d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/02n.png
    id: w02n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/03d.png
    id: w03d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/03n.png
    id: w03n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/04d.png
    id: w04d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/04n.png
    id: w04n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/09d.png
    id: w09d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/09n.png
    id: w09n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/10d.png
    id: w10d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/10n.png
    id: w10n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/11d.png
    id: w11d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/11n.png
    id: w11n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/13d.png
    id: w13d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/13n.png
    id: w13n
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/50d.png
    id: w50d
    type: BINARY
    resize: 400x400
    invert_alpha: true
  - file: /config/esphome/images/50n.png
    id: w50n
    type: BINARY
    resize: 400x400
    invert_alpha: true

# =========================
# Fonts (default only)
# =========================
font:
  - file: "gfonts://Inter@700"
    id: my_default_font
    size: 26
  - file: "gfonts://Inter@700"
    id: my_default_font_big
    size: 104

# =========================
# Globals to store last known values
# =========================
globals:
  - id: last_outside_temp
    type: float
    initial_value: '0.0'
  - id: last_outside_humidity
    type: float
    initial_value: '0.0'
  - id: last_living_temp
    type: float
    initial_value: '0.0'
  - id: last_living_humidity
    type: float
    initial_value: '0.0'

# =========================
# Text sensors (HA)
# =========================
text_sensor:
  - platform: homeassistant
    entity_id: sensor.outside_details
    id: outside_details
    internal: true

  - platform: homeassistant
    entity_id: sensor.outside_icon
    id: outside_icon
    internal: true

# =========================
# Numeric sensors (HA)
# =========================
sensor:
  - platform: homeassistant
    entity_id: sensor.living_room_temperature
    id: living_temp
    internal: true

  - platform: homeassistant
    entity_id: sensor.living_room_humidity
    id: living_humidity
    internal: true

  - platform: homeassistant
    entity_id: sensor.outside_temperature
    id: outside_temp
    internal: true

  - platform: homeassistant
    entity_id: sensor.outside_humidity
    id: outside_humidity
    internal: true

# =========================
# Time for French date
# =========================
time:
  - platform: homeassistant
    id: esptime

# =========================
# Display SPI
# =========================
spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

display:
  - platform: waveshare_epaper
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin:
      number: GPIO4
      inverted: true
    reset_pin: GPIO2
    model: 7.50inv2
    update_interval: 60s
    lambda: |-
      // ======================
      // DATE (FRENCH)
      // ======================
      auto t = id(esptime).now();
      if (t.year >= 2025) {
        const char* mois[12] = {"JANVIER","FEVRIER","MARS","AVRIL","MAI","JUIN","JUILLET","AOUT","SEPTEMBRE","OCTOBRE","NOVEMBRE","DECEMBRE"};
        char date_buffer[64];
        snprintf(date_buffer, sizeof(date_buffer), "%02d %s %04d",
                t.day_of_month,
                mois[t.month - 1],
                t.year);
        it.printf(40, 20, id(my_default_font), "%s", date_buffer);
      } else {
        it.printf(40, 20, id(my_default_font), "Connexion HA...");
      }

      // x = coordonnée horizontale de la ligne
      int x_line = 400;
      int y_start = 60;
      int y_end = 420;
      it.line(x_line, y_start, x_line, y_end);

      // ======================
      // OUTSIDE TEMP (LEFT, BIG)
      // ======================
      if (!isnan(id(outside_temp).state))
        id(last_outside_temp) = id(outside_temp).state;  // update last value
      it.printf(40, 60, id(my_default_font_big), "%.1f°c", id(last_outside_temp));

      // Outside humidity
      if (!isnan(id(outside_humidity).state))
        id(last_outside_humidity) = id(outside_humidity).state;
      it.printf(40, 170, id(my_default_font), "%.1f%%", id(last_outside_humidity));

      if (id(outside_details).has_state())
        it.printf(40, 200, id(my_default_font), "%s", id(outside_details).state.c_str());
      else
        it.printf(40, 200, id(my_default_font), "No data");


      if (id(outside_icon).has_state()) {
        // prepend "w" to the MQTT value
        std::string key = "w" + std::string(id(outside_icon).state.c_str());

        // now check which image matches dynamically
        if (key == "w01d") it.image(40, 250, id(w01d));
        else if (key == "w01n") it.image(40, 250, id(w01n));
        else if (key == "w02d") it.image(40, 250, id(w02d));
        else if (key == "w02n") it.image(40, 250, id(w02n));
        else if (key == "w03d") it.image(40, 250, id(w03d));
        else if (key == "w03n") it.image(40, 250, id(w03n));
        else if (key == "w04d") it.image(40, 250, id(w04d));
        else if (key == "w04n") it.image(40, 250, id(w04n));
        else if (key == "w09d") it.image(40, 250, id(w09d));
        else if (key == "w09n") it.image(40, 250, id(w09n));
        else if (key == "w10d") it.image(40, 250, id(w10d));
        else if (key == "w10n") it.image(40, 250, id(w10n));
        else if (key == "w11d") it.image(40, 250, id(w11d));
        else if (key == "w11n") it.image(40, 250, id(w11n));
        else if (key == "w13d") it.image(40, 250, id(w13d));
        else if (key == "w13n") it.image(40, 250, id(w13n));
        else if (key == "w50d") it.image(40, 250, id(w50d));
        else if (key == "w50n") it.image(40, 250, id(w50n));
        else it.printf(40, 250, id(my_default_font), "No icon");
      } else {
        it.printf(40, 250, id(my_default_font), "No icon");
      }

      // ======================
      // RIGHT COLUMN: LIVING ROOM
      // ======================
      int x = 430;
      int y = 60;
      int line = 40;

      it.printf(x, y, id(my_default_font), "Salon");
      y += line;

      // Living room temperature
      if (!isnan(id(living_temp).state))
        id(last_living_temp) = id(living_temp).state;
      it.printf(x, y, id(my_default_font), "%.1f°c", id(last_living_temp));
      y += line;

      // Living room humidity
      if (!isnan(id(living_humidity).state))
        id(last_living_humidity) = id(living_humidity).state;
      it.printf(x, y, id(my_default_font), "%.1f%%", id(last_living_humidity));
      y += line;
